name: Mirror Latest Release to KlothoPlatform/klotho

on:
  workflow_dispatch:
    inputs:
      tag-name:
        required: true
        description: the version tag that will be mirrored to KlothoPlatform/klotho (e.g. "v0.5.15")
  release:
    types:
      - published
jobs:
  mirror-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Details
        id: getRelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tag_name="${{ github.event.inputs.tag-name }}"
          if [ -z "${tag_name}" ]; then
            tag_name="$(echo "$GITHUB_REF" | cut -d/ -f3)"
          fi
          
          release_info=$(gh release -R ${GITHUB_REPOSITORY} view ${tag_name} \
              --json "name,body,isDraft,isPrerelease" \
              -q 'select(.isDraft == false and .isPrerelease == false)')
          if [ -z "$release_info" ]; then
            echo "published release ${tag_name} not found!"
            exit 1
          fi
          
          printf 'releaseInfo=%s\n' "$release_info" >> $GITHUB_OUTPUT

      - name: Download Release Artifacts
        id: downloadArtifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          sleep 10 # wait to minimize risk that the downloads won't yet be available for a newly published release
          gh release download ${{ fromJson(steps.getRelease.outputs.releaseInfo).name }} -R "$GITHUB_REPOSITORY" -p 'klotho_*'

      - name: Mirror Release to klothoplatform/klotho
        uses: softprops/action-gh-release@v1
        with:
          repository: klothoplatform/klotho
          token: ${{secrets.KLOTHO_PUBLIC_RELEASE_TOKEN}}
          name: ${{ fromJson(steps.getRelease.outputs.releaseInfo).name }}
          body: ${{ fromJson(steps.getRelease.outputs.releaseInfo).body }}
          draft: true
          files: ./**/klotho_*
          fail_on_unmatched_files: true
